### ISSUE TITLE
Bug Report: built-in replays

### ISSUE THREAD

**Issue by kistecool** [KeatonHoshida/HoloFunk-Public#2]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows, 64 variant.
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 with Kade 1.5.2
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Download a completely new copy of the game (both Coco and Fubuki work) and either open the replays in settings, or look at the files.
## Please describe your issue. Provide extensive detail and images if possible.
This isn't exactly a bug, but there are replays present in the game by default, probably from a final rundown to see if everything worked before posting. These should probably not be present so as to preserve space.

**Comment by awoo2u** [comment]
Replays will be removed next update.
