### ISSUE TITLE
Enhancement: Statistics in replays

### ISSUE THREAD

**Issue by kistecool** [KeatonHoshida/HoloFunk-Public#3]
## What is your suggestion, and why should it be implemented?
When looking at a replay of one of the Coco songs (I believe Friday Night,) the statistics that usually show the current score, combo breaks, accuracy, and grade are absent save for at the very end for a split second. Surely these could be computed in real-time based on the replay data, unless it's easier to even include them in the replay files themselves.

**Comment by awoo2u** [comment]
This is Kade Dev's responsibility if anything, he did mention replays won't be entirely accurate to your original play-through.
