### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by GokHyujae** [KeatonHoshida/HoloFunk-Public#4]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
4.0.2

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No steps involved. Consistently happens whenever I play the Coco songs.

## Please describe your issue. Provide extensive detail and images if possible.
Have an issue with FnF in general where no sound will play at all unless I switch my sampling rate to 4.41KHz because all the .ogg files are 4.41KHz. All the other songs in the mod will play perfectly except for the Coco songs. The music and voices will just cut out and in during certain parts.

**Comment by awoo2u** [comment]
This is the first time I saw someone address this. Have you tried re-downloading?

**Comment by GokHyujae** [comment]
I've tried:
-Fresh downloads
-Disabling audio enhancements
-Switching audio devices
-Admin/compatibility mode

Before I switched my sampling rate, I used to run it on a virtual machine running an unactivated W10 and it played all the audio fine through there.

**Comment by awoo2u** [comment]
> I've tried:
> -Fresh downloads
> -Disabling audio enhancements
> -Switching audio devices
> -Admin/compatibility mode
> 
> Before I switched my sampling rate, I used to run it on a virtual machine running an unactivated W10 and it played all the audio fine through there.

Try reinstalling or updating drivers. But it seems this isn't an issue with the game. So I'll be closing this.
